version: '3'

services:
  node1:
    image: cassandra:latest
    container_name: nodo1-cassandra
    ports:
      - "9042:9042"
    hostname: nodo1 
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_AUTO_BOOTSTRAP=false"
      - "CASSANDRA_AUTHENTICATOR=PasswordAuthenticator"
      - "CASSANDRA_AUTHORIZER=CassandraAuthorizer"
      - "CASSANDRA_ROLE_MANAGER=CassandraRoleManager"
      - "CASSANDRA_PASSWORD_VALIDATOR=PasswordValidator"

    restart: always
    volumes:
      - ./data/node1:/var/lib/cassandra
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./auth/nodo1/cqlshrc:/root/.cassandra/cqlshrc
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node2:
    image: cassandra:latest
    container_name: nodo2-cassandra
    hostname: nodo2
    ports:
      - "9043:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"

    restart: always
    volumes:
      - ./data/node2:/var/lib/cassandra
      - ./auth/nodo2/cqlshrc:/root/.cassandra/cqlshrc
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node3:
    image: cassandra:latest
    container_name: nodo3-cassandra
    hostname: node3
    ports:
      - "9044:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"  
    restart: always
    volumes:
      - ./data/node3:/var/lib/cassandra
      - ./auth/nodo3/cqlshrc:/root/.cassandra/cqlshrc
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
    volumes:
      - ./init-scripts/01-keyspace.cql:/docker-entrypoint-initdb.d/01-keyspace.cql
      - ./init-scripts/load-keyspace.sh:/docker-entrypoint-initdb.d/load-keyspace.sh
    command: /bin/bash -c "/docker-entrypoint-initdb.d/load-keyspace.sh"
